[package]
name = "consumer_producer"
version = "0.1.0"
authors = ["Hillel Aryeh Sreter <Hillel.s@neuroblade.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
